
export enum ComponentModule {
  RegistrationModule,
  AdmissionModule,
  RegistrationListComponent,
  DoctorModule,
  DepartmentModule,
  DepartmentListModule,
  DepartmentTypeModule,
  DepartmentTypeListModule,
  HospitalDetailsModule,
  HospitalDetailsListModule,
  Licencemodule,
  LicenceListModule,
  BuildingModule,
  BuildingListModule,
  FloorModule,
  FloorListModule,
  WardTypeModule,
  WardTypeListModule,
  SurgeryTypeModule,
  SurgeryTypeListModule,
  AdmissionTypeModule,
  AdmissionTypeListModule,
  DischargeTypeModule,
  DischargeTypeListModule,
  DeliveryTypeModule,
  DeliveryTypeListModule,
  OperationTypeModule,
  OperationTypeListModule,
  PregnantTreatmentModule,
  PregnantTreatmentListModule,
  VaccineTypeModule,
  VaccineTypeListModule,
  ConfirmationModal,
  DiseaseTypeModule,
  DiseaseTypeListModule,
  DocumentRepository,
  PackagesModule,
  PackagesListModule,
  DashboardComponent,
  AdmissionListModule,
  WardTypeModal,
  BillingModule,
  BillingListModule,
  PrescriptionModule,
  PrescriptionListModule,
  BedModal,
  ForgetPasswordModal,
  OtModule,
  OtListModule,
  DischargeCertificateModule,
  DischargeCertificateListModule,
  DoctorListModule,
  SaveMessageModal,
  WardModule,
  WardListModule,
  BedModule,
  BedListModule,
  OtTypeModule,
  OtTypeListModule,
  NewBornModule,
  NewBornListModule,
  AdmissionConfirmationModal,
  PriceModule,
  PriceListModule,
  GenericActionModal,
  DischargeModalModule,
  BillingPreviewModule,
  ApproverModule,
  ApproverListModule,
  ApprovalModule,
  ApprovalListModule,
  ApprovedListModule,
  ApprovalDashboardListModule,
  ApprovalDashboardModule,
  RejectedModule,
  RejectedListModule,
  DocumentListModule,
  DocumentModule,
  SchedulingListModule,
  SchedulingModule,
  UserTypeListModule,
  UserTypeModule,
  UserListModule,
  UserModule,
  PermissionModule,
  PermissionListModule,
  AssignPermissionModule,
  AssignPermissionListModule
}










